[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Cameron Hartman <cameron.hartman081@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14" 